### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by zhanglv0209** [wac81/Book_DeepLearning_Practice#2]
因为同事推荐，买了您的书，下载下来的代码报各种错误，代码不全，既然选择了开源，希望你奉献出完整版的代码，这才是真正开源的精神，要不然买你的书，不能很好的运行，那么你的书和其他的书又有啥区别呢？

**Comment by zhanglv0209** [comment]
您也可以像其他作者一样建一个qq群，方便与读者交流，让更多门外的读者进入到深度学习这个领域，这样的作者才能真正体现出你写这本书的价值和意义所在

**Comment by wac81** [comment]
1.我没有任何义务给你完整代码。
2.开源部分代码，只是让你们不要手动输入。
3.这种方式恰恰让你们懂得代码的机制，而不是直接拿来就能跑的程序，这反而锻炼了你们读写程序的能力。
4.请直接说具体问题。
